version: '3'

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - php
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./html:/var/www/html
  #     - ./snippets:/etc/nginx/conf.d/snippets12

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    command: bash -c "php -S 0.0.0.0:80 & php queue.php"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    platform: linux/x86_64
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "database", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

# networks:
#   levart_db:
#     driver: bridge
volumes:
  postgres:
    driver: local